target:test

test:test.cpp AbstractHex.cpp  AbstractHex.h HexVector.cpp HexVector.h HexArray1D.cpp HexArray1D.h HexAdapter.cpp HexAdapter.h
	g++ test.cpp AbstractHex.cpp HexVector.cpp HexArray1D.cpp HexAdapter.cpp -o try -std=c++11
	./try
